jobs:
- job:
  displayName: images
  pool:
    vmImage: windows-latest

  steps:
  - checkout: self
    persistCredentials: true

  - task: AzureFileCopy@6
    inputs:
      SourcePath: './images' #caminho dos arquivos das imagens
      azureSubscription: 'portal' #nome do service connection
      Destination: 'AzureBlob'  #tipo de destino
      storage: 'storagesteste' #nome do storage account
      ContainerName: 'img' #nome do container